-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."squad" add column "auto_created" boolean
--  not null default 'true';
